engrisk2voca/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vocabulary.urls', namespace='vocabulary'))
]

vocabulary/urls.py
from django.urls import path
from .views import HomePage, quiz


app_name = 'vocabulary'

urlpatterns = [
    path('', HomePage.as_view(), name='home'),
    path('quiz', quiz, name='quiz'),
]

vocabulary/models.py
from django.db import models

# Create your models here.
class Vocabulary(models.Model):
    word = models.CharField(max_length=255)
    definition = models.TextField()
    meaning = models.TextField() 

vocabulary/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Vocabulary
import random


# Create your views here.
class HomePage(LoginRequiredMixin, View):
    login_url = '/admin/login/'

    def get(self, request):
        vocabularys = list(Vocabulary.objects.all())
        random.shuffle(vocabularys)
        return render(request, 'home.html', {'vocabularys' : vocabularys})

@login_required(login_url="/admin/login/")
def quiz(request):
    vocabularys = list(Vocabulary.objects.all())
    random.shuffle(vocabularys)
    quizlist = list(vocabularys[:10])
    return render(request, 'quiz.html', {'vocabularys' : quizlist})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Engrisk2Voca</title>
    <link rel="shortcut icon" href="https://img.icons8.com/nolan/64/brick.png" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'js/main.js' %}">
</head>

<body>
    
    <a href="{% url 'vocabulary:home' %}">
        <h1 id="title">Cần gì hơn khi đã có em?</h1>
    </a>
    <a href="{% url 'vocabulary:quiz' %}">
        <h4 id="hahalolo">fromtinhtutewithlove</h4>
    </a>
    
    <hr>
    <center>
        {% block main %}
        {% endblock %}
    </center>
    <div class="footer">
        <span id="credit">Tính thiếu Nhi</span>
    </div>
</body>


</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
<ul>
    {% for vocabulary in vocabularys %}
    <li class="sentence">
        <div id='word-{{ vocabulary.word }}' class="word-sentence"><strong>-</strong></div>
        <div class="definition-sentence"> {{ vocabulary.definition }} </div>
        <div class="btn-sentence"><button id='showword-{{ vocabulary.word }}'>Show</button></div>
        <script>
            document.getElementById("showword-{{ vocabulary.word }}").addEventListener("click", function (id) {
                document.getElementById("word-{{ vocabulary.word }}").innerHTML = "<strong>{{ vocabulary.word }}</strong>";
            });
            document.getElementById("showword-{{ vocabulary.word }}").addEventListener("dblclick", (id) => {
                window.getSelection().selectAllChildren(document.getElementById("word-{{ vocabulary.word }}"));
                document.execCommand("copy");
            });
        </script>

    </li>
    {% endfor %}
</ul>
<script type="text/javascript">
    
</script>
{% endblock %}

templates/quiz.html
{% extends 'base.html' %}
{% load static %}

{% block main %}

<ul class='listanswer'>
    <p><strong>*</strong> Dòng này là để chú thích một cái gì đó thôi, nhưng không biết nên gì cái gì :)))))</p>
    {% for vocabulary in vocabularys %}
    <li class="sentence">
        <input type="text" placeholder="Type your answer here!" class='answer left' name='{{ vocabulary.word }}' value=""/>
        <div class="definition-sentence right"> {{ vocabulary.definition }} </div>
    </li>
    {% endfor %}
    <button onclick="myFunction()" id="submit">Submit</button>
</ul>

<script>
    function myFunction() {
        var lst = document.getElementsByClassName("answer");
        for (var i = 0; i < 10; i++) {
            var val = lst[i].getAttribute("name");
            if (lst[i].value == val){
                lst[i].style.backgroundColor = "#21bf73";
            }
            else {
                lst[i].value = val;
                lst[i].style.backgroundColor = '#d92027';
            }
        }
        // lst.forEach(element => {
        //     var val = element.getAttribute("name");
        //     if (element.value == val){
        //         element.style.backgroundColor = "#21bf73";
        //     }
        //     else {
        //         element.value = val;
        //         element.style.backgroundColor = '#d92027';
        //     }
        // });
        document.getElementById('hahalolo').innerHTML = 'Quiz Again?';
    }
</script>

{% endblock %}